server:
  port: 9090
  servlet:
    session:
      tracking-modes: cookie

spring:
  application:
    name: auth-server
    debug: true

  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9090

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.authorization.web.authentication: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always