server:
  port: 8082

spring:
  application:
    name: tenant-service
  datasource:
    url: jdbc:h2:mem:tenantdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: h2
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  oauth2:
    resource-server:
      jwt:
        issuer-uri: http://localhost:9090

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: tenant-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

h2:
  console:
    enabled: true
    path: /h2-console